repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: flake8
    -   id: name-tests-test
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
        files: requirements-dev.txt
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.2
    hooks:
    -   id: autopep8
        args:
        - -i
        - --ignore=E309,E501
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.3
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/Yelp/detect-secrets
    rev: 0.10.5
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: tests/.*
