repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: fix-encoding-pragma
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
        files: requirements-dev.txt
-   repo: git://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    -   id: autopep8
        args: ['-i', '--ignore=E309,E501']
-   repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.7.6
    hooks:
    -   id: flake8
        exclude: ^docs
-   repo: git://github.com/asottile/reorder_python_imports
    sha: v1.0.1
    hooks:
    -   id: reorder-python-imports
-   repo: git://github.com/Yelp/detect-secrets
    sha: 0.9.1
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: tests/.*
