language: python

matrix:
  include:
  - env: TOXENV=py27-default
  - env: TOXENV=py27-fido
  - env: TOXENV=py35-default
    python: python3.5
  - env: TOXENV=py35-fido
    python: python3.5
  - env: TOXENV=cover
  - env: TOXENV=docs
  - env: TOXENV=flake8

install:
- "pip install tox coveralls"
script:
- tox -e $TOX_ENV
after_success:
- coveralls
# Faster runs on container based infrastucture
sudo: false
