language: python
matrix:
  include:
  - env: TOXENV=py27
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36
  - env: TOXENV=cover
  - env: TOXENV=docs
  - env: TOXENV=flake8
install: pip install tox coveralls
script: tox
after_success: if [ "$TOXENV" == "cover" ]; then coveralls; fi
sudo: false
