language: python
os: linux

python: "3.7"

jobs:
  include:
  - python: "2.7"
    env: SKIP_PYYAML_INSTALL=y
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    env: PUBLISH_COVERAGE=y
  - env: TOXENV=docs
  - env: TOXENV=pre-commit
  - env: TOXENV=benchmark
  - env: TOXENV=mypy
  allow_failures:
  - env: TOXENV=benchmark
  fast_finish: true

install: pip install tox tox-travis coveralls
before_script: |
  # building pyyaml package with 2.7 shows incompatibility
  if [ "${SKIP_PYYAML_INSTALL:-n}" == "y" ]; then
    sed -i -e 's/pyyaml --global-option="--without-libyaml"//' requirements-dev.txt
  fi
script: tox
after_success: |
  if [ "${PUBLISH_COVERAGE:-n}" == "y" ]; then coveralls; fi
  if [ "${TOXENV}" == "benchmark" ]; then
    echo $(ls .benchmarks/*/0001_benchmark.json) $(cat .benchmarks/*/0001_benchmark.json | nc termbin.com 9999)
  fi
