language: python
matrix:
  include:
  - python: "3.5"
    env: TOX_ENV=py35
env:
- TOX_ENV=py27
- TOX_ENV=cover
- TOX_ENV=docs
- TOX_ENV=flake8
install:
- "pip install tox coveralls"
script:
- tox -e $TOX_ENV
after_success:
- coveralls
# Faster runs on container based infrastucture
sudo: false
