language: python
os: linux

python: "3.8"

jobs:
  include:
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - python: "3.9"
  - env: TOXENV=cover
  - env: TOXENV=docs
  - env: TOXENV=pre-commit
  - env: TOXENV=benchmark
  allow_failures:
  - env: TOXENV=benchmark
  fast_finish: true

before_install:
  - "pip install -U pip"
  - "python setup.py install"
install: pip install tox tox-travis coveralls
script: tox
after_success: |
  if [ "$TOXENV" == "cover" ]; then coveralls; fi
  if [ "${TOXENV}" == "benchmark" ]; then
    echo $(ls .benchmarks/*/0001_benchmark.json) $(cat .benchmarks/*/0001_benchmark.json | nc termbin.com 9999)
  fi
