language: python

matrix:
  include:
  - env: TOXENV=py27-default
    python: "2.7"
  - env: TOXENV=py27-fido
    python: "2.7"
  - env: TOXENV=py27-fido-requests2dot17
    python: "2.7"

  - env: TOXENV=py35-default
    python: "3.5"
  - env: TOXENV=py35-fido
    python: "3.5"

  - env: TOXENV=py36-default
    python: "3.6"
  - env: TOXENV=py36-fido
    python: "3.6"

  - env: TOXENV=cover
  - env: TOXENV=docs
  - env: TOXENV=pre-commit
  - env: TOXENV=mypy
    python: "3.6"

install:
- "pip install tox coveralls"
script:
- tox
after_success:
- if [ "$TOXENV" == "cover" ]; then coveralls; fi
